ALTER TABLE design_document ADD CONSTRAINT design_document_pkey PRIMARY KEY USING INDEX idx_design_document_id;
ALTER TABLE design_document_input_snapshot ADD CONSTRAINT design_document_input_snapshot_pkey PRIMARY KEY USING INDEX idx_design_document_input_snapshot_id;
ALTER TABLE design_document_revision ADD CONSTRAINT design_document_revision_pkey PRIMARY KEY USING INDEX idx_design_document_revision_id;
ALTER TABLE design_document_input_snapshot ADD CONSTRAINT design_document_input_snapshot_task_id_key UNIQUE USING INDEX idx_design_document_input_snapshot_task_id;
ALTER TABLE design_document_revision ADD CONSTRAINT design_document_revision_source_task_id_key UNIQUE USING INDEX idx_design_document_revision_source_task_id;
ALTER TABLE design_document_revision ADD CONSTRAINT design_document_revision_input_snapshot_id_key UNIQUE USING INDEX idx_design_document_revision_input_snapshot_id;
